services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: builder
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
      - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.builder.rule=Host(`builder.rafaelcardoso.co.uk`)"
      - "traefik.http.routers.builder.entrypoints=websecure"
      - "traefik.http.routers.builder.tls.certresolver=letsencrypt"
      - "traefik.http.services.builder.loadbalancer.server.port=3000"
    networks:
      - proxy

networks:
  proxy:
    external: true
